[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions_ota.csv
board_upload.flash_size = 4MB
lib_extra_dirs = ../lib
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -I../include
upload_protocol = esptool
monitor_speed = 115200

[env:esp32dev_ota]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions_ota.csv
board_upload.flash_size = 4MB
lib_extra_dirs = ../lib
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -I../include
upload_protocol = espota
upload_port = 192.168.x.x
upload_flags =
    --auth=
    --port=3232
monitor_speed = 115200
monitor_port = network
